version: "3"

services: 
  web:
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes: 
  portainer-data: